plugins:
  openid_connect_rbx_enabled:
    default: false
  openid_connect_rbx_discovery_document:
    default: "https://apis.roblox.com/oauth/.well-known/openid-configuration"
  openid_connect_rbx_client_id:
    default: ""
  openid_connect_rbx_client_secret:
    default: ""
  openid_connect_rbx_rp_initiated_logout:
    default: false
  openid_connect_rbx_rp_initiated_logout_redirect:
    default: ""
  openid_connect_rbx_allow_association_change:
    default: false
  openid_connect_rbx_overrides_email:
    default: false
  # openid_connect_rbx_overrides_name:
  #   default: false
  # openid_connect_rbx_overrides_username:
  #   default: false
  openid_connect_rbx_overrides_avatar:
    default: false
  openid_connect_rbx_authorize_scope:
    default: "openid profile"
  openid_connect_rbx_verbose_logging:
    default: false
  openid_connect_rbx_token_scope:
    default: ""
  openid_connect_rbx_error_redirects:
    default: ""
    type: list
    list_type: secret
  openid_connect_rbx_authorize_parameters:
    default: ""
    type: list
    list_type: compact
  openid_connect_rbx_claims:
    default: ""
    textarea: true
  openid_connect_rbx_match_by_email:
    default: false
