plugins:
  openid_connect_discovery_document:
    default: ""
  openid_connect_client_id:
    default: ""
  openid_connect_client_secret:
    default: ""
  openid_connect_authorize_scope:
    default: "openid"
  openid_connect_token_scope:
    default: ""
  openid_connect_use_userinfo:
    default: true
  openid_connect_error_redirects:
    default: ''
    type: list
    list_type: secret
